apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility
spec:
  selector:
    matchLabels:
      app: utility
  replicas: 1
  template:
    metadata:
      labels:
        app: utility
    spec:
      containers:
      - name: utility
        image: 327361568963.dkr.ecr.us-east-1.amazonaws.com/k8s-utility:e2bb704-1562020086
